import 'package:get/get.dart';

class CitiesController extends GetxController {
  RxList<String> allCities = <String>[
    // Major Metropolitan Cities
    'Karachi',
    'Lahore',
    'Islamabad',
    'Rawalpindi',
    'Faisalabad',
    'Multan',
    'Gujranwala',
    'Peshawar',
    'Quetta',

    // Large Cities
    'Bahawalpur',
    'Sargodha',
    'Sialkot',
    'Sukkur',
    'Larkana',
    'Sheikhupura',
    'Rahim Yar Khan',
    'Jhang',
    'Dera Ghazi Khan',
    'Gujrat',
    'Sahiwal',
    'Mardan',
    'Kasur',
    'Okara',
    'Mingora',
    'Nawabshah',
    'Chiniot',
    'Kamoke',
    'Mirpur Khas',
    'Burewala',
    'Kohat',
    'Khanewal',
    'Dera Ismail Khan',
    'Turbat',
    'Muzaffargarh',
    'Abbottabad',
    'Bahawalnagar',
    'Khuzdar',
    'Pakpattan',
    'Khairpur',
    'Chakwal',
    'Gojra',
    'Mandi Bahauddin',

    // Medium-sized Cities
    'Jacobabad',
    'Shikarpur',
    'Mianwali',
    'Bhakkar',
    'Charsadda',
    'Kandhkot',
    'Kotri',
    'Kot Addu',
    'Dadu',
    'Tando Allahyar',
    'Tando Adam',
    'Jhelum',
    'Muridke',
    'Hasan Abdal',
    'Kamalia',
    'Umerkot',
    'Ahmedpur East',
    'Kotli',
    'Wah Cantonment',
    'Taxila',
    'Rohri',
    'Mansehra',
    'Swabi',
    'Jaranwala',
    'Chishtian',
    'Attock',
    'Vehari',
    'Wazirabad',
    'Karak',
    'Khanpur',
    'Hub',
    'Badin',
    'Lodhran',
    'Daska',
    'Khushab',
    'Chaman',
    'Turbat',
    'Zhob',
    'Gwadar',
    'Nowshera',

    // Northern Areas & AJK
    'Muzaffarabad',
    'Gilgit',
    'Skardu',
    'Chitral',
    'Swat',
    'Mansehra',
    'Abbottabad',
    'Murree',
    'Kaghan',
    'Naran',
    'Shogran',
    'Battagram',
    'Besham',
    'Shangla',

    // Balochistan Cities
    'Khuzdar',
    'Quetta',
    'Sibi',
    'Loralai',
    'Zhob',
    'Gwadar',
    'Pasni',
    'Turbat',
    'Panjgur',
    'Kharan',
    'Nushki',
    'Chagai',
    'Kalat',
    'Mastung',
    'Ziarat',

    // KPK Cities
    'Peshawar',
    'Mardan',
    'Charsadda',
    'Nowshera',
    'Swabi',
    'Kohat',
    'Bannu',
    'Dera Ismail Khan',
    'Swat',
    'Malakand',
    'Dir',
    'Buner',
    'Shangla',
    'Haripur',
    'Abbottabad',
    'Mansehra',
    'Batagram',
    'Kohistan',
    'Torghar',

    // Punjab Cities (additional)
    'Nankana Sahib',
    'Sheikhupura',
    'Gujrat',
    'Mandi Bahauddin',
    'Sialkot',
    'Narowal',
    'Gujranwala',
    'Lahore',
    'Kasur',
    'Okara',
    'Sahiwal',
    'Pakpattan',
    'Vehari',
    'Khanewal',
    'Multan',
    'Lodhran',
    'Bahawalpur',
    'Bahawalnagar',
    'Rahim Yar Khan',
    'Dera Ghazi Khan',
    'Muzaffargarh',
    'Layyah',
    'Bhakkar',
    'Khushab',
    'Mianwali',
    'Sargodha',
    'Chakwal',
    'Jhelum',
    'Rawalpindi',
    'Attock',
    'Fateh Jang',
    'Talagang',
    'Rasoolpur Tarar'
    
    // Sindh Cities (additional)
    'Karachi',
    'Hyderabad',
    'Sukkur',
    'Larkana',
    'Nawabshah',
    'Mirpur Khas',
    'Jacobabad',
    'Shikarpur',
    'Khairpur',
    'Dadu',
    'Sanghar',
    'Thatta',
    'Badin',
    'Umerkot',
    'Tharparkar',
    'Matiari',
    'Tando Muhammad Khan',
    'Jamshoro',
    'Kashmore',
    'Ghotki',
    'Naushahro Feroze',
    'Shaheed Benazirabad',
    'Sujawal',
    'Tando Allahyar',

    // AJK Cities
    'Muzaffarabad',
    'Mirpur',
    'Bhimber',
    'Kotli',
    'Rawalakot',
    'Bagh',
    'Hattian',
    'Neelum Valley',
    'Haveli',
    'Poonch',
    'Sudhnati',

    // Gilgit-Baltistan
    'Gilgit',
    'Skardu',
    'Chilas',
    'Ghizer',
    'Ghanche',
    'Astore',
    'Diamer',
    'Kharmang',
    'Shigar',
    'Nagar',
    'Gupis',
    'Yasin',
    'Ishkoman',
    'Hunza',
    'Gojal',

    // Popular Hill Stations
    'Murree',
    'Nathia Gali',
    'Ayubia',
    'Shogran',
    'Naran',
    'Kaghan',
    'Kalam',
    'Malam Jabba',
    'Chitral',
    'Kalash Valley',
    'Ziarat',
    'Quetta',
    'Fairy Meadows',

    // Historical & Cultural Cities
    'Taxila',
    'Harappa',
    'Mohenjo-daro',
    'Thatta',
    'Makli',
    'Lahore Fort',
    'Badshahi Mosque',
    'Shalimar Gardens',
    'Rohtas Fort',
    'Ranikot Fort',
    'Katas Raj Temples',
    'Takht-i-Bahi',
    'Moenjodaro',

    // Industrial & Commercial Hubs
    'S.I.T.E Karachi',
    'Korangi',
    'Landhi',
    'North Karachi',
    'Saddar',
    'Gulberg',
    'DHA',
    'Clifton',
    'Gulshan-e-Iqbal',
    'Johar Town',
    'Wapda Town',
    'Model Town',
    'Cantt',
    'Samanabad',
    'Iqbal Town',
    'Township',
    'Garden Town',

    // Educational Cities
    'Taxila',
    'Lahore',
    'Karachi',
    'Islamabad',
    'Faisalabad',
    'Multan',
    'Peshawar',
    'Quetta',

    // Border Cities
    'Wagah',
    'Torkham',
    'Chaman',
    'Khokhrapar',
    'Gurdaspur',

    // Port Cities
    'Karachi',
    'Gwadar',
    'Port Qasim',
    'Keti Bandar',
    'Jiwani',
    'Ormara',

    // Airports (Major)
    'Jinnah International Karachi',
    'Allama Iqbal International Lahore',
    'Islamabad International',
    'Bacha Khan International Peshawar',
    'Quetta International',
    'Multan International',
    'Faisalabad International',
    'Sialkot International',
    'Gwadar International',

    // Tourist Destinations
    'Hunza Valley',
    'Skardu',
    'Fairy Meadows',
    'Nanga Parbat',
    'Deosai Plains',
    'K2 Base Camp',
    'Shangrila Resort',
    'Saif-ul-Mulook',
    'Ansoo Lake',
    'Ratti Gali Lake',
    'Mahodand Lake',
    'Kund Malir Beach',
    'Ormara Beach',
    'Astola Island',
    'Churna Island',
    'Manora Island',

    // Religious Sites
    'Data Darbar Lahore',
    'Badshahi Mosque',
    'Faisal Mosque Islamabad',
    'Shah Rukn-e-Alam Multan',
    'Baha-ud-din Zakariya',
    'Lal Shahbaz Qalandar',
    'Shah Abdul Latif Bhitai',
    'Sachal Sarmast',
    'Abdullah Shah Ghazi',
    'Mangho Pir',
    'Kartarpur Sahib',
    'Nankana Sahib',
    'Hasan Abdal',
    'Katas Raj',
    'Takht-i-Bahi',

    // Administrative Divisions (Headquarters)
    'Peshawar Division',
    'Malakand Division',
    'Mardan Division',
    'Kohat Division',
    'Hazara Division',
    'Bannu Division',
    'Dera Ismail Khan Division',
    'Lahore Division',
    'Gujranwala Division',
    'Rawalpindi Division',
    'Sargodha Division',
    'Faisalabad Division',
    'Multan Division',
    'Bahawalpur Division',
    'Dera Ghazi Khan Division',
    'Sahiwal Division',
    'Karachi Division',
    'Hyderabad Division',
    'Sukkur Division',
    'Mirpur Khas Division',
    'Larkana Division',
    'Shaheed Benazirabad Division',
    'Quetta Division',
    'Kalat Division',
    'Makran Division',
    'Nasirabad Division',
    'Sibi Division',
    'Zhob Division',
    'Loralai Division',
  ].obs;
}
